### ISSUE TITLE
PBS scheduler errors are not output to the user

### ISSUE THREAD

**Issue by SeanBryan51** [ACCESS-NRI/hpcpy#34]
* hpcpy version: 0.6.0
* Python version: 3.9.20
* Operating System: Gadi (Rocky Linux)

### Description

Error messages from `qsub` don't seem to be output to the user when submitting the job via `hpcpy`.

### What I Did

```
cat << EOF > foo.pbs
#PBS -N test
#PBS -l wd
#PBS -l walltime=00:01:00
#PBS -l ncpus=1
#PBS -l mem=1GB
#PBS -j oe
echo 'foobar'
EOF
python -c "import hpcpy; hpcpy.get_client().submit('foo.pbs', variables={'FOO': 'bar'})"
```

The above commands output:

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/scratch/tm70/sb8430/conda/envs/benchcab_run_model/lib/python3.9/site-packages/hpcpy/client/pbs.py", line 138, in submit
    return super().submit(
  File "/scratch/tm70/sb8430/conda/envs/benchcab_run_model/lib/python3.9/site-packages/hpcpy/client/base.py", line 107, in submit
    result = self._shell(cmd)
  File "/scratch/tm70/sb8430/conda/envs/benchcab_run_model/lib/python3.9/site-packages/hpcpy/client/base.py", line 180, in _shell
    result = shell(cmd)
  File "/scratch/tm70/sb8430/conda/envs/benchcab_run_model/lib/python3.9/site-packages/hpcpy/utilities.py", line 32, in shell
    return sp.run(
  File "/scratch/tm70/sb8430/conda/envs/benchcab_run_model/lib/python3.9/subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['qsub', '-v', 'FOO=bar', 'foo.pbs']' returned non-zero exit status 32.
```

Submitting the job directly with `qsub` by running:

```
cat << EOF > foo.pbs
#PBS -N test
#PBS -l wd
#PBS -l walltime=00:01:00
#PBS -l ncpus=1
#PBS -l mem=1GB
#PBS -j oe
echo 'foobar'
EOF
qsub -v FOO=bar foo.pbs
```

outputs the additional error message:

```
qsub: Error: You have not requested a project to charge for this job. You can supply a project through the PROJECT environment variable, the -P option to qsub, or the #PBS -P directive in your job script.
```

**Comment by bschroeter** [comment]
OK, this looks to be the default behaviour of subprocess, whereby it does not output the `stderr` attribute when printed.

<img width="1029" alt="image" src="https://github.com/user-attachments/assets/792a19c0-b260-4361-9a11-7cf814804d52">

Technically this isn't a bug as the exception is being raised and bubbles up to the user who should handle the exception in their own code. However, I'll admit that the user needs more information than an error code.

<img width="1098" alt="image" src="https://github.com/user-attachments/assets/324b3304-d56b-4ff1-8e8b-1060e5339a46">


I'll create a new exception class for these, with something useful for an hpcpy user.
